stages:
  - synth_st
  - pnr_st
  - pack_st

variables:
  DIRS: "01-Basics/00-Init \
         01-Basics/01-LED \
         01-Basics/02-Button \
         01-Basics/03-Counter \
         01-Basics/04-Trigger \
         01-Basics/05-Debounce \
         02-Audio/01-Sound"
#         80-Test/10-passthru"

synth:
  stage: synth_st
  image: hdlc/ghdl:yosys
  before_script:
    - yosys --version
  script:
    - >
      for i in $DIRS;
      do set -e;
      pushd ${i};
      make synth;
      popd;
      done
  artifacts:
    paths:
      - "*/*/*.json"
    expire_in: 1 week

pnr:
  stage: pnr_st
  image: hdlc/nextpnr:ecp5
  before_script:
    - apt update -qq && DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends make
    - nextpnr-ecp5 --version
  script:
    - >
      for i in $DIRS;
      do set -e;
      pushd ${i};
      touch *.json;
      make pnr;
      popd;
      done
  artifacts:
    paths:
      - "*/*/*.config"
    expire_in: 1 week

pack:
  stage: pack_st
  image: hdlc/prjtrellis
  before_script:
    - ecppack --version
  script:
    - >
      for i in $DIRS;
      do set -e;
      pushd ${i};
      touch *.json;
      touch *.config;
      make pack;
      popd;
      done
  artifacts:
    paths:
      - "*/*/*.bit"
    expire_in: 1 week
