variables:
  DIRS: "01-Basics/00-Init \
         01-Basics/01-LED \
         01-Basics/02-Button \
         01-Basics/03-Counter \
         01-Basics/04-Trigger \
         01-Basics/05-Debounce \
         02-Audio/01-Sound"
#         80-Test/10-passthru"

synth:
  image: hdlc/impl:prjtrellis
  before_script:
    - yosys        --version
    - nextpnr-ecp5 --version
    - ecppack      --version
  script:
    - >
      for i in $DIRS;
      do set -e;
      pushd ${i};
      make synth;
      make pnr;
      make pack;
      popd;
      done

  artifacts:
    paths:
      - "*/*/*.json"
      - "*/*/*.config"
      - "*/*/*.bit"
    expire_in: 42 days
