name: (Single Job) Build bitstreams using OpenSource toolchain

on:
  push:

env:
  DIRS: "01-Basics/00-Init \
         01-Basics/01-LED \
         01-Basics/02-Button \
         01-Basics/03-Counter \
         01-Basics/04-Trigger \
         01-Basics/05-Debounce \
         02-Audio/01-Sound"
#         80-Test/10-passthru"

jobs:
  synth-pnr-pack:
    runs-on: ubuntu-latest
    container: hdlc/impl:prjtrellis
    steps:
      - uses: actions/checkout@v2
      - name: Synthesis, PnR, Gen. Bitstream
        run: |
          yosys --version
          for i in ${{ env.DIRS }};
          do set -e;
          bash -c "set -e; pushd ${i}; make synth; make pnr; make pack; popd;"
          done
      - name: Upload Gatelevel Netlist
        uses: actions/upload-artifact@v2
        with:
          name: gatelevel-netlist
          path: "*/*/*.json"
          retention-days: 42
      - name: Upload Layout Netlist
        uses: actions/upload-artifact@v2
        with:
          name: place-and-route
          path:  "*/*/*.config"
          retention-days: 42
      - name: Upload Bitstream
        uses: actions/upload-artifact@v2
        with:
          name: bitstream
          path: "*/*/*.bit"
          retention-days: 42
